name: Daily IPTV Scraper

on:
  schedule:
    # Ogni giorno alle 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch: # Permette di lanciare manualmente la workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python multiscrapergrouped.py

      - name: Commit generated playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add multigroup.m3u
          git commit -m "Aggiornamento automatico playlist"
          git push
        env:
          # Serve token per push automatico
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
